server:
  port: ${HTTP_PORT:8988}
  error:
    include-message: always

springdoc:
  swagger-ui:
    display-request-duration: true
    operationsSorter: method
    tagsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  jpa:
    open-in-view: false

timezone:
  location: Europe/London
